export const cohorts = [
  {
    id: 1,
    slug: "cohort-1-0",
    name: "Cohort 1.0",
    applicants: "2,500",
    admitted: "1,500",
    graduated: "450",
    declined: "50",
    startDate: "1/02/2025",
    endDate: "2/05/2025",
    applicantDetails: [
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Lagos",
        date: "2/05/2025",
        status: "Admitted",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Lagos",
        date: "2/05/2025",
        status: "Pending",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Lagos",
        date: "2/05/2025",
        status: "Declined",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Lagos",
        date: "2/05/2025",
        status: "Graduated",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Lagos",
        date: "2/05/2025",
        status: "Admitted",
      },
    ],
  },
  {
    id: 2,
    slug: "cohort-2-0",
    name: "Cohort 2.0",
    applicants: "1,234",
    admitted: "9,507",
    graduated: "210",
    declined: "456",
    startDate: "2/05/2024",
    endDate: "2/08/2024",
    applicantDetails: [
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Admitted",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Admitted",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
    ],
  },
  {
    id: 3,
    slug: "cohort-3-0",
    name: "Cohort 3.0",
    applicants: "5,687",
    admitted: "1,009",
    graduated: "386",
    declined: "196",
    startDate: "2/05/2024",
    endDate: "2/12/2023",
    applicantDetails: [
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Imo",
        date: "2/12/2023",
        status: "Declined",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Imo",
        date: "2/12/2023",
        status: "Admitted",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Imo",
        date: "2/12/2023",
        status: "Declined",
      },
    ],
  },
  {
    id: 4,
    slug: "cohort-4-0",
    name: "Cohort 4.0",
    applicants: "2,500",
    admitted: "4,587",
    graduated: "123",
    declined: "510",
    startDate: "1/02/2025",
    endDate: "2/05/2023",
    applicantDetails: [
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Admitted",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Graduated",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Graduated",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Graduated",
      },
    ],
  },
  {
    id: 5,
    slug: "cohort-5-0",
    name: "Cohort 5.0",
    applicants: "25,079",
    admitted: "1,500",
    graduated: "450",
    declined: "123",
    startDate: "1/02/2025",
    endDate: "2/05/2022",
    applicantDetails: [
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "UI/UX Design",
        level: 2,
        location: "Delta",
        date: "2/05/2022",
        status: "Admitted",
      },
    ],
  },
  {
    id: 6,
    slug: "cohort-6-0",
    name: "Cohort 6.0",
    applicants: "25,079",
    admitted: "1,500",
    graduated: "450",
    declined: "385",
    startDate: "1/02/2025",
    endDate: "2/05/2022",
    applicantDetails: [
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Declined",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Admitted",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Declined",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Declined",
      },
    ],
  },
  {
    id: 7,
    slug: "cohort-7-0",
    name: "Cohort 7.0",
    applicants: "25,079",
    admitted: "1,500",
    graduated: "450",
    declined: "123",
    startDate: "1/02/2025",
    endDate: "2/05/2022",
    applicantDetails: [
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Admitted",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "Software Development",
        level: 1,
        location: "Ogun",
        date: "2/08/2024",
        status: "Pending",
      },
    ],
  },
  {
    id: 8,
    slug: "cohort-8-0",
    name: "Cohort 8.0",
    applicants: "25,079",
    admitted: "1,500",
    graduated: "450",
    declined: "978",
    startDate: "1/02/2025",
    endDate: "2/05/2022",
    applicantDetails: [
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Graduated",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Admitted",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Graduated",
      },
      {
        applicantName: "Ayo Lawal",
        applicantEmail: "ayolawal@gmail.com",
        course: "Data Analysis",
        level: 1,
        location: "Oyo",
        date: "2/05/2023",
        status: "Graduated",
      },
    ],
  },
  {
    id: 9,
    slug: "cohort-9-0",
    name: "Cohort 9.0",
    applicants: "25,079",
    admitted: "1,500",
    graduated: "450",
    declined: "123",
    startDate: "1/02/2025",
    endDate: "2/05/2022",
    applicantDetails: [
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "UI/UX Design",
        level: 2,
        location: "Delta",
        date: "2/05/2022",
        status: "Admitted",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "UI/UX Design",
        level: 2,
        location: "Delta",
        date: "2/05/2022",
        status: "Pending",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "UI/UX Design",
        level: 2,
        location: "Delta",
        date: "2/05/2022",
        status: "Admitted",
      },
      {
        applicantName: "Favour Ola",
        applicantEmail: "favourola@gmail.com",
        course: "UI/UX Design",
        level: 2,
        location: "Delta",
        date: "2/05/2022",
        status: "Admitted",
      },
    ],
  },
  {
    id: 10,
    slug: "cohort-10-0",
    name: "Cohort 10.0",
    applicants: "25,079",
    admitted: "1,500",
    graduated: "450",
    declined: "096",
    startDate: "1/02/2025",
    endDate: "2/05/2022",
    applicantDetails: [
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Declined",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Declined",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Admitted",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Declined",
      },
      {
        applicantName: "Musa Garba",
        applicantEmail: "musagarba@gmail.com",
        course: "UI/UX Design",
        level: 3,
        location: "Port-Harcourt",
        date: "2/05/2022",
        status: "Admitted",
      },
    ],
  },
];
